#My brother walked by on me doing this and went "I would rather watch you work than do (xyz) thing", and I responded "so you would rather watch me have a million brain farts?"
#and he laughed and said "yeah, that is just kinda how coding goes", and thats honestly how I felt coding this lol.
#This is just from my memory of when I watched Alice in Wonderland when I was 8, so I'm definatly not right in a lot aspects lol..
#However I am a fantasy writer so I did have fun writing the story for this.
#Even if I had quit w/o saving so I had to write the code again. (hashtag)SaveYourWork ( ´･･)ﾉ(._.`)
#I did have a lot of plans for this but i ran out of time. Oops.
import time
import random

print(" |              |\n" * 3)
print("You poor child, you fell down.. To Wonderland..")
time.sleep(3)
playerName = input("Might I know your name? : ").title()
print(" |              |\n" * 3)
print("A beautiful name.. Be careful my child..")
time.sleep(5)

def GameOver():
    print("\n" * 40)
    print(playerName+"... You poor child...")
    time.sleep(2)
    print("You couldn't survive Wonderland...")
    time.sleep(2)
    print("Do you wish to take on Wonderland one more? Or are you done going insane in the maze of madness?")
    decison = input("Try again? (Y/N) ")
    if decison == "Y":
        print("Good luck child... Try not to loose your s@nity... :)")
        time.sleep(2)
        hp = 50
        Area1Desc()
    if decison == "N":
        print("Very well. May you sleep in peace,", playerName+".")
        time.sleep(5)
        exit()
hp = 50
class Enemy:
     def __init__(self, mName, mAttackHi, mAttackLo, mHp):
         self.mName = mName
         self.mAttackHi = mAttackHi
         self.mAttackLo = mAttackLo
         self.mHp = mHp
                                    
     def Encounter1(self):
         print(f"You encountered:", self.mName)
         time.sleep(1)
         def EnemyAtk():
             global healedHp
             global hp #I'm aware it is kinda a bad habit to use global variables but nothing else worked. This is the case with all the global variables you'll see... (¬_¬ )
             if healedHp == True:
                 hp = 50
                 healedHp = False
                 
             damageTaken = random.randint(int(self.mAttackLo), int(self.mAttackHi))
             time.sleep(2)
             print(f"The", self.mName, "attacked you...")
                
             if damageTaken >= hp:
                 time.sleep(2)
                 print(f"...The", self.mName, "did", damageTaken, "points of damage...")
                 time.sleep(2)
                 print("...Which killed you.")
                 time.sleep(3)
                 print("Which.. Killed.. You..")
                 time.sleep(3)
                 GameOver()
             if damageTaken < hp:
                 time.sleep(2)
                 print(f"...The", self.mName, "did", damageTaken, "points of damage.")
                 time.sleep(2)
                 youHealthCalc = int(hp) - damageTaken
                 hp = youHealthCalc
                 print("You are currently at", str(hp), "hp.")
                 Battle()
         def Battle():
             global heartCards
             print("")
             decision = input("You do (ATK/FLEE): ")
             if decision == "ATK":
                 print("You attacked...")
                 damageDealt = random.randint(1, 15)
                 time.sleep(2)
                 if damageDealt >= int(self.mHp):
                     print("...You hit and dealt", damageDealt, "and killed him!")
                     time.sleep(2)
                     heartCardsGot = random.randint(10, 20)
                     hrtCardsCalc = heartCards + heartCardsGot
                     heartCards = hrtCardsCalc
                     print("you got", str(heartCardsGot), "heart cards.")
                     heartCards = hrtCardsCalc
                     time.sleep(2)
                 if damageDealt < int(self.mHp):
                     print("...You hit and dealt", damageDealt, "point(s) of damage.")
                     enemyHealthCalc = int(self.mHp)-damageDealt
                     time.sleep(2)
                     self.mHp = enemyHealthCalc
                     print("The enemy has", str(self.mHp), "HP left.")
                     EnemyAtk()
             if decision == "FLEE":
                 print("You tried to flee the battle...")
                 whyWountYouJustFleeYouLittle = random.randint(1, 2)
                 if whyWountYouJustFleeYouLittle == 2:
                     print("...And you successfuly fleed. You gained no heart cards however.")
                     time.sleep(2)
                 else:
                     print("...But you couldn't get away!")
                     EnemyAtk()
         Battle()

COH = Enemy(f"Card of Hearts", "20", "1", "40")
ROSE = Enemy(f"Talking Roses", "10", "1", "15")
BLTR  = Enemy(f"Blue Tree", "10", "1", "30")

heartCards = 0
page1 = False
page1chk = False
pagemis = False
pagemischk = False
healedHp = False
prop = False
CHCcounter = 0
BRP = False
def Area5Final():# I decided to end it here because I ran out of time
    print("   |          ¦                         |\n" * 20)
    print("<<‹‹    ^                  ⁔ ⁔          ››>>")
    time.sleep(3)
    print("You climb the steep rocks, you're exausted..")
    time.sleep(3)
    print("You're very wet, it like you just walked through the sea. (And in a sense, you did.)")
    time.sleep(3)
    print("You pass through the waterfall.")
    time.sleep(3)
    print("Its a cavern with a dead end.")
    time.sleep(3)
    print("")
    print('"What comes down... But never comes up?" you say, semi-expectantly.')
    time.sleep(3)
    print('"Yes.. What is the answer?" Says a soft voice from the distance.')
    time.sleep(3)
    def finale():
        answer = input("What comes up but never comes down? (All caps)")
        if answer == "RAIN":
            print("...")
            time.sleep(4)
            print("...Wrong...")
            time.sleep(4)
            print("...Its you :)")
            time.sleep(5)
            print("...")
            time.sleep(5)
            print("You pass out instantly...")
            time.sleep(5)
            print("\n" * 40)
            print("_🌳_______🌲🌲__")
            time.sleep(5)
            print("You're.. Home?")
            time.sleep(5)
            print("But what about that letter?")
            time.sleep(1)
            print("What even was that?")
            time.sleep(1)
            print("Everything in your bag is gone.. Was that a dream?")
            time.sleep(1)
            print("What about-")
            time.sleep(1)
            print("Quiet. You're home now. Aren't you?")
            time.sleep(4)
            print("Everyones worried sick about you. Aren't they?")
            time.sleep(4)
            print("GO.")
            time.sleep(1)
            print("HOME.")
            time.sleep(5)
            print("Maybe you can go back someday.. Some.. DAy?")
            time.sleep(5)
            print("\n" * 40)
            time.sleep(6)
            print("...The wonderland thoughts are racing through my head")
            time.sleep(1)
            print("I csnt escape them")
            time.sleep(1)
            print("HAve I gone MAD?")
            time.sleep(1)
            print("\n" * 40)
            time.sleep(6)
            print("...Yeah, maybe i can return someday...")
            input("Press Enter to quit:) ")
            exit()
        else:
           print("...")
           time.sleep(4)
           print("...Try again")
           time.sleep(4)
           finale()
    finale()
def Area4Desc():
    print("  🍰  ☕☕ 🍩   ")
    print("-----------------")
    print("|~~~~~~~~~~~~~~~|")
    print("|               |")
    print("|               |")
    time.sleep(3)
    print("Once you touch the fire, you are suddenly engulfed within it.")
    time.sleep(3)
    print("You hear a soft voice from a distance...")
    time.sleep(3)
    print("")
    print('"'+playerName+'... You are almost.. h.."')
    time.sleep(3)
    print("")
    print("You hear the voice drift away as it is speaking.. You start to feel.. Dizzy..")
    time.sleep(3)
    print("You fall down, and when you get up, you see...")
    time.sleep(3)
    print("A.. Tea.? A tea party?")
    time.sleep(3)
    print("A man wearing a comedically large, green hat appears infront of you..")
    time.sleep(3)
    print("")
    print('"Oh deah, what do we haveh here?" The man says inspecting you.')
    time.sleep(3)
    print("")
    print('"A.. Lost young one.." You say as you get up...')
    time.sleep(3)
    print('"And who might you be?"')
    time.sleep(3)
    print("")
    print('"Oho! Well you might call me the Mad Hatter!" He says while skipping to a table.')
    time.sleep(3)
    print('"Care for some tea young lad?"')
    time.sleep(3)
    print("")
    print('"No Im okay, I should rea-"')
    time.sleep(2)
    print("")
    print('"But its tea time! You cant just leave during tea time now can you son?"')
    time.sleep(3)
    print("")
    print('"Im sorry Mr.Hatter, but I simply must-"')
    time.sleep(3)
    print("")
    print('"Ah no no no! That wont do!" He says as he pulls you by your shirt sleeve.')
    time.sleep(3)
    print("")
    print("You're suddenly sat at a table. Its all neatly organized.")
    time.sleep(3)
    print("Theres lots of tea and food on the table.")
    time.sleep(3)
    print("")
    print('"What may you want? We have plent of choices!" He says with a smile.')
    time.sleep(3)
    teaTime = 1
    def teaTime():
        print("Theres tea, cookies, biscuts, croissants, and cake. Are you really hungry?")
        print('"TEA" = Tea, "CKIE" = Cookies, "BSCT" = Biscuts, "CRST" = Croissants, "CAKE" = Cake "NO" = "No thank you."')
        decison = input("You choose: ")
        if decison == "TEA":
            print("you decided to have some tea...")
            time.sleep(3)
            print("...Its actually fairly pleasant. It's a nice herbal tea.")
            time.sleep(3)
            print("...Do you want to have anymore?")
            teaTime()
        if decison == "CKIE":
            print("You decided to have some cookies...")
            time.sleep(3)
            print("...It's oatmeal raisin.. You don't like oatmeal raisin..")
            time.sleep(3)
            print("You pretend to enjoy it.. Yuck..")
            time.sleep(3)
            teaTime()
        if decison == "BSCT":
            print("You decided to have some biscuts...")
            time.sleep(3)
            print("The biscuts are soft, almost like a pillow, you fairly enjoy it...")
            time.sleep(3)
            print("...Do you want to have anymore?")
            teaTime()
        if decison == "CRST":
            print("You decided to have some croissants...")
            time.sleep(3)
            print("The croissants are nice and airy, very crispy...")
            time.sleep(3)
            print("Do you want anymore?")
            teaTime()
        if decison == "CAKE":
            print("You decided to have some cake...")
            time.sleep(3)
            print("Its a sweet vanilla cake with strawberries on top. Its a bit too sweet for your taste, but its still nice.")
            time.sleep(3)
            teaTime()
        if decison == "NO":
            print("You told the Mad Hatter you weren't hungry nor thirsty...")
    teaTime()
    time.sleep(3)
    print("")
    print('"Proposterous!", he shouts, he was about to say something else before he was cut off...')
    time.sleep(3)
    print("")
    print("A white rabbit in a hurry suddenly appears...")
    time.sleep(3)
    print("")
    print('"Mad Hatter! I am sorry I am late! I had lost my way!" the white rabbit says, panting.')
    time.sleep(3)
    print("")
    print('"Ah, need not worry! You are no later than this young fellow!" the Mad Hatter says while looking at you.')
    time.sleep(3)
    print("")
    print("You instantly recognize the rabbit. He's the rabbit you saw when you first entered.")
    time.sleep(3)
    print("")
    print('"He arrives here and he doesnt want to stay! During tea time! Can you beleive this boy!" He says, a bit sngry.')
    time.sleep(3)
    print("")
    print('"I am sorry Mr. Hatter, I am merely trying to get home!" You say, wanting to get out of this situation.')
    time.sleep(3)
    print("")
    print('"Well why not come the way you came? It should be simple!" The white rabbit says, oblivious')
    time.sleep(3)
    print("")
    print('"Well, you see I fell down a-"')
    time.sleep(2)
    print("")
    print('"Ah, heed not say another word!" The Mad Hatter says..')
    time.sleep(3)
    print('"Past the east waterfall, lies a deep cavern. When you speak to it, it shall let you through.."')
    time.sleep(3)
    print("")
    print('"What shall I say to it?"')
    time.sleep(3)
    print("")
    print('"What comes down.. But never comes up?"')
    time.sleep(3)
    print('"Would you like some more tea young lad?"')
    time.sleep(3)
    print("")
    print('"N- No thank you.." You quickly run, scared.')
    time.sleep(3)
    print("You run..")
    time.sleep(1)
    print("And run..")
    time.sleep(1)
    print("And.. Run..")
    time.sleep(1)
    print("...Run...")
    time.sleep(3)
    print("Until you come across a waterfall... Is this it?")
    time.sleep(3)
    print("\n" * 20)
    Area5Final()
def Area3Desc():
    global healedHp
    print("¯¯|¯¯|¯¯|¯¯|¯¯¯|¯¯|¯¯|¯¯|¯¯|¯¯¯|¯¯|¯¯¯¯")
    print("| |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹  |")
    print("| |  |  |   |  |  |  |   |  |  |  |   |")
    print("| |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹  |")
    print("| |  |  |   |  |  |  |   |  |  |  |   |")
    print("| |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹  |")
    print("| |  |  |   |  |  |  |   |  |  |  |   |")
    print("| |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹 |  |🌹  |")
    print("__|__|__|___|__|__|__|__|__|___|__|____")
    time.sleep(1)
    print("You w@ke up..")
    time.sleep(3)
    print("You don't feel like.. Y0urself?")
    time.sleep(3)
    print("Like.. Your in someone else's body.. Though your |n your own.?")
    time.sleep(3)
    print("Your on a bed in a house. The walls are pink with roses on the white stripes. It looke like an average house, but everything is all cutsy yet being.. Erie..")
    time.sleep(4)
    print("The bed you woke up on has blue and white stripes with hearts. The matress is soft, and its quite comfortable. You feel.. Rested? (Hp restored)")
    healedHp = True
    time.sleep(4)
    print("It doesn't look like theres anyone here, but yet you feel eyes on you.")
    time.sleep(4)
    print("Theres something on the bed with a note. You start reading...")
    time.sleep(4)
    print("")
    print('"Hello! You were lying on the ground so I put you in here to rest. If you dont see me, your probably wrooong. - CH cat :~)"')
    print("")
    input("Press Enter to continue")
    print("Next to the paper theres a.. pocket watch? The pocket watch is made out of gold. Emblazened with an.. Emblem of.. somewhere? With red roses painted on the rim.")
    time.sleep(4)
    print("You take both the paper and the pocket watch with you just in case.")
    time.sleep(4)
    def Area3DnrmDesc():
        print("You decided to go to the Dining room...")
        time.sleep(3)
        print("The wallpaper is the same as the rest of the house. Your starting to get sick of it.")
        time.sleep(3)
        print("...The table is set up perfectly, All the silverware is set up just right, the plates are in the right spot, and its honestly beautiful.")
        time.sleep(3)
        print("Its as if it was set up for guests, but there seemingly isn't anyone here.")
        time.sleep(3)
        print("The table itself is pink, with purple accents on its legs.")
        time.sleep(3)
        print("The chairs are pink aswell, with blue cushions. Its like a unicorn was made into a dining room.")
        time.sleep(3)
        print("You should go look around for clues.")
        def Area3Dnrm():
            global CHCcounter
            global BRP
            global prop
            print("Do you wish to go to A diffrent r0om or look around for clues")
            print('Type "BAG" to look inside your bag. Type "STAT" to look at your stats.')
            print("")
            decison = input("ROOM/LOOK: ")
            if decison == "STAT":
                print('MAX HP:', hp)
                print("He/art Cards:", heartCards)
                print("InsAnity:: ????????")
                time.sleep(3)
                Area3Lvrm()
            if decison == "BAG":
                if prop == False:
                    Area3Bag()
                if prop == True:
                    Area3BagProp()
                if BRP == True:
                    Area3BagBRP()
                Area3Lvrm()
            if decison == "ROOM":
                print("    Which room do you wish to go to?")
                print('    "KTCH" = Kitchen, "BDRM" = Bedroom, "LVRM" = Living room')
                decison = input("Go to: ")
                if decison == "BDRM":
                    print("You go to the bedroom...")
                    time.sleep(2)
                    print("...It looks about the same as when you last were there...")
                    time.sleep(3)
                    Area3Bdrm()
                if decison == "KTCH":
                    Area3KtchDesc()
                if decison == "LVRM":
                    Area3DnrmDesc()
            if decison == "LOOK":
                print("You decided to have a look around...")
                time.sleep(3)
                if prop == True and CHCcounter == 1:
                    print("Theres a weird candle painting on the wall, It almost feels like its flickering.")
                    time.sleep(3)
                    print("You touch the painting...")
                    time.sleep(3)
                    print("...But nothing happends.")
                    time.sleep(3)
                    print("You move the painting to find...")
                    time.sleep(3)
                    print("...A rose?")
                    time.sleep(2)
                    print("And it has..")
                    time.sleep(3)
                    print("...A.. Blue..? It has.. One blue rose petal?")
                    time.sleep(3)
                    print("You prick off the blue rose petal for keeps.")
                    BRP = True
                    time.sleep(3)
                    print("Something started talking to you again...")
                    time.sleep(3)
                    print("")
                    print('"LEt the rrrose petal burrn up in flames :}"')
                    time.sleep(4)
                    print("")
                    print('"WHO ARE YOU?!" You yelled, confused and startled.')
                    time.sleep(4)
                    print("")
                    print("You see yellow eyes inside of the cavern that the rose wass in.")
                    time.sleep(4)
                    print("")
                    print('"Im just an ordinary cat you seee.." He says as a smile reveals itself..')
                    time.sleep(4)
                    print("")
                    print('"No! For you are a mere pair of topaz-enlaidened eyes beyond the face..!" ...Wait...')
                    time.sleep(4)
                    print("")
                    print("...What did you just say? Did you just...")
                    time.sleep(4)
                    print("")
                    print('"You are already speaking of Wonderland mouth, imprrressive..." the cat says as he reveals his full body.')
                    time.sleep(4)
                    print("")
                    print('"The petal you have in your hands will burn in flames, with the assistants of a child that is.."')
                    time.sleep(4)
                    print("")
                    print('"For must you fuel the fire.. A gateway appears.. Where soon, the tea becomes the fire.."')
                    time.sleep(4)
                    print("")
                    print("You.. Almost.. Understand him in what he's saying?")
                    print("You knod confusingly, I guess now is time to go to the kitchen again..?")
                    time.sleep(4)
                    Area3Dnrm()
                else:
                    print("...But maybe you should look in the other rooms first.")
                    time.sleep(3)
                    Area3Dnrm()
        Area3Dnrm()
        
    def Area3LvrmDesc():
        print("You decided to go yo the Living room..")
        time.sleep(3)
        print("The wallpaper is the same as the rest of the house. Your starting to get sick of it.")
        time.sleep(3)
        print("Theres a smell of.. Incense? Even though theres none burning at the moment.")
        time.sleep(3)
        print("The couch is pink with white dots, with a few decorative pillows along the same design caliber.")
        time.sleep(3)
        print("The TV looks like its from the 70's, and.. Its not plugged in.. With no outlet in sight.. Well huh.")
        time.sleep(3)
        print("You wonder how they used this TV without it being plugged in?")
        time.sleep(3)
        print("The carpet is blue, which somehow clashes horribly with the couch.")
        time.sleep(3)
        print("You should get moving.")
        time.sleep(2)
        def Area3Lvrm():
            global prop
            print("Do you wish to go to A diffrent r0om or look around for 1tems?")
            print('Type "BAG" to look inside your bag. Type "STAT" to look at your stats.')
            print("")
            decison = input("ROOM/LOOK: ")
            if decison == "STAT":
                print('MAX HP:', hp)
                print("He/art Cards:", heartCards)
                print("InsAnity:: ????????")
                time.sleep(3)
                Area3Lvrm()
            if decison == "BAG":
                if prop == False:
                    Area3Bag()
                if prop == True:
                    Area3BagProp()
                if BRP == True:
                    Area3BagBRP()
                Area3Lvrm()
            if decison == "ROOM":
                print("    Which room do you wish to go to?")
                print('    "KTCH" = Kitchen, "BDRM" = Bedroom, "DNRM" = Dining room')
                decison = input("Go to: ")
                if decison == "BDRM":
                    print("You go to the bedroom...")
                    time.sleep(2)
                    print("...It looks about the same as when you last were there...")
                    time.sleep(3)
                    Area3Bdrm()
                if decison == "KTCH":
                    Area3KtchDesc()
                if decison == "DNRM":
                    Area3DnrmDesc()
            if decison == "LOOK":
                print("You decided to look around...")
                time.sleep(3)
                if prop == False:
                    print("You had looked around for a bit when you had a look under the couch...")
                    time.sleep(3)
                    print("...Theres a propane tank under here?")
                    time.sleep(3)
                    print("Who on earth would put a propane tank under a couch?")
                    time.sleep(3)
                    print("You end up taking it anyway, it could be important.")
                    time.sleep(3)
                    prop = True
                    Area3Lvrm()
                if prop == True:
                    print("It appears you already found the intresting items in this room.")
                    time.sleep(2)
                    print("Maybe you should look at one of the other rooms?")
                    time.sleep(2)
                    Area3Lvrm()
        Area3Lvrm()

    def Area3KtchDesc():
        global CHCcounter
        print("You decided to go to the kitchen..")
        time.sleep(3)
        print("The kitchen has the same wallpaper as the rest of the house. You're kinda starting to get tired of it.")
        time.sleep(4)
        print("The stove has hearts as the temprature control knobs. They look untouched and new. The stove is brand new as well.")
        time.sleep(4)
        print("The fridge has heart card magnets all over it.")
        time.sleep(4)
        print("Although you can see through the gaps of the magnets that the fridge itself is.. Black?")
        time.sleep(4)
        print("Has anyone actually cooked anything in here?")
        time.sleep(4)
        print("Oh well, you should get moving.")
        time.sleep(2)
        def Area3Ktch():
            global CHCcounter
            print("Do you wish to go to A diffrent r0om or look around for 1tems?")
            print('Type "BAG" to look inside your bag. Type "STAT" to look at your stats.')
            print("")
            decison = input("ROOM/LOOK: ")
            if decison == "STAT":
                print('MAX HP:', hp)
                print("He/art Cards:", heartCards)
                print("InsAnity:: ????????")
                time.sleep(3)
                Area3Ktch()
            if decison == "BAG":
                if prop == False:
                    Area3Bag()
                if prop == True:
                    Area3BagProp()
                if BRP == True:
                    Area3BagBRP()
                Area3Ktch()
            if decison == "ROOM":
                print("    Which room do you wish to go to?")
                print('    "LVRM" = Living room, "BDRM" = Bedroom, "DNRM" = Dining room')
                decison = input("Go to: ")
                if decison == "BDRM":
                    print("You go to the bedroom...")
                    time.sleep(2)
                    print("...It looks about the same as when you last were there...")
                    time.sleep(3)
                    Area3Bdrm()
                if decison == "LVRM":
                    Area3LvrmDesc()
                if decison == "DNRM":
                    Area3DnrmDesc()
            if decison == "LOOK":
                print("You decided to have a look around the kitchen...")
                time.sleep(3)
                if prop == False:
                    print("...You ended up trying to turn on the stove, and...")
                    time.sleep(3)
                    print("...Its not hooked up to propane. Great. Can you find propane anywhere?")
                    time.sleep(3)
                    Area3Ktch()
                if prop == True:
                    print("...You tried to turn on the stove, and...")
                    time.sleep(3)
                    print("...Its not hooked up to propane. But you have the propane you found earlier, do you wish to hook it up to the stove?")
                    time.sleep(3)
                    decison = input("Hook it up? (Y/N): ")
                    if decison == "Y":
                        if CHCcounter == 0:
                            print("You hooked up the propane...")
                            time.sleep(3)
                            print("...And when you turned the knob...")
                            time.sleep(3)
                            print("...Purple.. Fire? Purple fire came out of the stove. You stood confused when you hear...")
                            time.sleep(3)
                            print('"YEs.. Purrple.. My faavorite color.. HeEhe ^>^"')
                            time.sleep(3)
                            print("Startled, you look all around you, but theres nothing.. You turn the stove off before that happends again.")
                            CHCcounter = 1
                            time.sleep(3)
                            Area3Ktch()
                        if CHCcounter == 1 and BRP == False:
                            print("You were gonna hook it up.. But from what happended last time, You decided not to chaNce it.")
                            time.sleep(2)
                            Area3Ktch()
                        if CHCcounter == 1 and BRP == True:
                            print("You hooked up the propane.")
                            time.sleep(3)
                            print("This time the flame burned a mix of pink and purple.")
                            time.sleep(3)
                            print("You put the petal in as the feline described.")
                            time.sleep(3)
                            print("The flame erupted into a massive fire, you stepped way back.")
                            time.sleep(3)
                            print('"Yessss... You now musst step in, let it not burrn you ⁐`-´⁐"')
                            time.sleep(3)
                            print("Without much care anymore, you touch the fire...")
                            time.sleep(3)
                            print("\n" * 40)
                            Area4Desc()
                    if decison == "N":
                        print("You decided not to hook it up.")
                        time.sleep(2)
                        Area3Ktch()
        Area3Ktch()
        
    def Area3Bdrm():
        print("Do you wish to go to A diffrent r0om or go b@ck to sleep¿")
        print('Type "BAG" to look inside your bag. Type "STAT" to look at your stats.')
        print("")
        decison = input("ROOM/SLEP: ")
        if decison == "STAT":
            print('MAX HP:', hp)
            print("He/art Cards:", heartCards)
            print("InsAnity:: ????????")
            time.sleep(3)
            Area3Bdrm()
        if decison == "BAG":
            def Area3BagBRP():
                print("You had a look in your bag...")
                time.sleep(2)
                print("...Theres the pocket watch, the paper, and the propane tank. Which one do you wanna look at?")
                time.sleep(2)
                print('"PK" = Pocket watch, "PPR" = Paper, "PROP" = Propane tank, BLRP = Blue rose petal, "BACK" = Go Back')
                decison = input("Look at: ")
                if decison == "PK":
                    print("You look at the pocket watch...")
                    time.sleep(3)
                    print("The pocket watch is about the size of a softball. It reads as.. 25:00? And its not moving? Well its usless at telling the time.")
                    time.sleep(4)
                    print("Thats if there were time here. It sure doesn't feel like theres a day/night cycle here.")
                    time.sleep(4)
                    print("What is that emblem emblazened into the watch? Why is it 25:00? Why is it.. Erie? So many quEstions, no one to answer them.")
                    time.sleep(4)
                if decison == "PPR":
                    print("You start reading the piece of paper..")
                    time.sleep(3)
                    print("")
                    print('"Hello! You were lying on the ground so I put you in here to rest. If you dont see me, your probably wrooong. - CHC :~)"')
                    print("")
                    input("Press Enter to continue")
                    print("You feel.. Lonely all of a sudden. You start wanting someone or something to talk to.")
                    time.sleep(3)
                    print("It feels like you spent years here, but its only been..")
                    time.sleep(3)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print("You.. You don't know.. You could have slept for a minute, You could have slept for 100 years.. You really don't.")
                    time.sleep(4)
                    print("But it doesn't matter how depressed of hopeless you feel. You just.. Move on... :(")
                    time.sleep(3)
                if decison == "PROP":
                    print("You looked at the propane tank...")
                    time.sleep(3)
                    print("...Its one of those little propane tanks you use for camping.")
                    time.sleep(3)
                    print("Its extremely dusty, and its full. Which means this hasn't been used. Why?")
                    time.sleep(3)
                if decison == "BLRP":
                    print("You looked at the blue rose petal...")
                    time.sleep(3)
                    print("...The cat's voice echoes through your mind...")
                    timw.sleep(3)
                    print("")
                    print('"Must you fuel the fire.. The tea becomes the fire.."')
                    time.sleep(3)
                    print("")
                    print("You.. Must keep to his word..")
                    time.sleep(3)
                    
                if decison == "BACK":
                    print("You decided not to look at anything.")
                    time.sleep(3)
            def Area3BagProp():
                print("You had a look in your bag...")
                time.sleep(2)
                print("...Theres the pocket watch, the paper, and the propane tank. Which one do you wanna look at?")
                time.sleep(2)
                print('"PK" = Pocket watch, "PPR" = Paper, "PROP" = Propane tank, "BACK" = Go Back')
                decison = input("Look at: ")
                if decison == "PK":
                    print("You look at the pocket watch...")
                    time.sleep(3)
                    print("The pocket watch is about the size of a softball. It reads as.. 25:00? And its not moving? Well its usless at telling the time.")
                    time.sleep(4)
                    print("Thats if there were time here. It sure doesn't feel like theres a day/night cycle here.")
                    time.sleep(4)
                    print("What is that emblem emblazened into the watch? Why is it 25:00? Why is it.. Erie? So many quEstions, no one to answer them.")
                    time.sleep(4)
                if decison == "PPR":
                    print("You start reading the piece of paper..")
                    time.sleep(3)
                    print("")
                    print('"Hello! You were lying on the ground so I put you in here to rest. If you dont see me, your probably wrooong. - CHC :~)"')
                    print("")
                    input("Press Enter to continue")
                    print("You feel.. Lonely all of a sudden. You start wanting someone or something to talk to.")
                    time.sleep(3)
                    print("It feels like you spent years here, but its only been..")
                    time.sleep(3)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print("You.. You don't know.. You could have slept for a minute, You could have slept for 100 years.. You really don't.")
                    time.sleep(4)
                    print("But it doesn't matter how depressed of hopeless you feel. You just.. Move on... :(")
                    time.sleep(3)
                if decison == "PROP":
                    print("You looked at the propane tank...")
                    time.sleep(3)
                    print("...Its one of those little propane tanks you use for camping.")
                    time.sleep(3)
                    print("Its extremely dusty, and its full. Which means this hasn't been used. Why?")
                    time.sleep(3)
                if decison == "BACK":
                    print("You decided not to look at anything.")
                    time.sleep(3)
            def Area3Bag():
                print("You had a look in your bag...")
                time.sleep(2)
                print("...Theres the pocket watch and the paper. Which one do you wanna look at?")
                time.sleep(2)
                print('"PK" = Pocket Watch, "PPR" = Paper, "BACK" = Go Back')
                decison = input("Look at: ")
                if decison == "PK":
                    print("You look at the pocket watch...")
                    time.sleep(3)
                    print("The pocket watch is about the size of a softball. It reads as.. 25:00? And its not moving? Well its usless at telling the time.")
                    time.sleep(4)
                    print("Thats if there were time here. It sure doesn't feel like theres a day/night cycle here.")
                    time.sleep(4)
                    print("What is that emblem emblazened into the watch? Why is it 25:00? Why is it.. Erie? So many quEstions, no one to answer them.")
                    time.sleep(4)
                if decison == "PPR":
                    print("You start reading the piece of paper..")
                    time.sleep(3)
                    print("")
                    print('"Hello! You were lying on the ground so I put you in here to rest. If you dont see me, your probably wrooong. - CHC :~)"')
                    print("")
                    input("Press Enter to continue")
                    print("You feel.. Lonely all of a sudden. You start wanting someone or something to talk to.")
                    time.sleep(3)
                    print("It feels like you spent years here, but its only been..")
                    time.sleep(3)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print(".")
                    time.sleep(1)
                    print("You.. You don't know.. You could have slept for a minute, You could have slept for 100 years.. You really don't.")
                    time.sleep(4)
                    print("But it doesn't matter how depressed of hopeless you feel. You just.. Move on... :(")
                    time.sleep(3)
                if decison == "BACK":
                    print("You decided not to look at anything.")
                    time.sleep(3)
            if prop == False:
                Area3Bag()
            if prop == True:
                Area3BagProp()
            if BRP == True:
                Area3BagBRP()
            Area3Bdrm()
        if decison == "ROOM":
            print("    Which room do you wish to go to?")
            print('    "LVRM" = Living room, "KTCH" = Kitchen, "DNRM" = Dining room')
            decison = input("Go to: ")
            if decison == "KTCH":
                Area3KtchDesc()
            if decison == "LVRM":
                Area3LvrmDesc()
            if decison == "DNRM":
                Area3DnrmDesc()
        if decison == "SLEP":
            print("You decide to sleep a bit more..")
            time.sleep(4)
            print("You wake up feeling rested..")
            healedHp = True
            time.sleep(3)
            Area3Bdrm()
            
    Area3Bdrm()
            

def Area2Desc():
    global pagemis
    global pagemischk
    print("[.]⁅.⁆⁽.⁾<.>{.}")
    time.sleep(1)
    print("After you woke up, you felt.. Small..er? You're not at the same place either.")
    time.sleep(3)
    print("Your in a room of.. Mirrors? With each of the reflections looking diffrent?")
    time.sleep(3)
    print("With no clear way out, you decide to..")
    time.sleep(2)
    def Area2():
        print("Do you want to 3xplore? or look closely at the mirrOrs?")
        print('Type "BAG" to look inside your bag. Type "STAT" to look at your stats.')
        print("")
        decison = input("EXPL/MIRR: ")
        if decison == "STAT":
            print('MAX HP:', hp)
            print("Heart Cards:", heartCards)
            print("InsAnity:: ????????")
            time.sleep(3)
            Area2()
            
        if decison == "BAG":
            global pagemischk
            print("You had a look in your bag..")
            time.sleep(2)
            if pagemischk == False:
                print("All there is is the single torn peice of paper.")
                read = input("Read it again? (Y/N):")
                if read == "Y":
                    print("")
                    print("I don.t know where i am. 1t fels like i m ln e dreA\nthis worid i's 1nsame, i do\nESCAP3??????")
                    print("")
                    input("Press Enter to continue")
                    Area2()
                if read == "N":
                    print("You decided not to read it.")
                    time.sleep(2)
                    Area2()
            if pagemischk == True:
                print("But nothing is in it now. You kinda miss the paper..? But its still best to move on.")
                time.sleep(2)
                Area2()

        if decison == "MIRR":
            global pagemis
            print("You tried looking into the m1rror closer..")
            time.sleep(2)
            if pagemis == False:
                print("But you feel like.. You have to d0 something first?")
                time.sleep(2)
                Area2()
            if pagemis == True:
                print("...You see just a reflection of yourself. But...")
                time.sleep(3)
                print("...It starts spEAking to you‽!")
                time.sleep(3)
                print("")
                print("ʸᴼᵁᴿ ᴼᴺᴱ ᴼᶠ ᵁˢ ᴺᴼᵂ :)))")
                time.sleep(0.1)
                print("")
                print("ⱼₒᵢₙ ᵤₛ ᵢₙ WₒₙDₑᵣₗₐₙD")
                time.sleep(0.1)
                print("")
                print("ᏇᏋ ᎮᏗᎥᏁᏖ ᎥᏁ ᏒᏋᎴ")
                time.sleep(0.1)
                print("")
                print('ʯou barely have any time to respond before "|T" takes you in the mirror.')
                time.sleep(3)
                print("\n" * 40)
                Area3Desc()
        if decison == "EXPL":
            print("You decided to explore a little more...")
            time.sleep(2)
            print("...There doesn't seem to be any enemies here at least.. whew...")
            time.sleep(2)
            whatHappends = random.randint(1,2)
            if whatHappends == 1:
                print("...However you find.. F-Faces? They are saying.. Something?")
                time.sleep(3)
                print('"BΣᄃӨMΣ ЩӨПDΣЯᄂΛПD FӨЯΣVΣЯ"')
                time.sleep(2)
                print("You got scared and ran in the opposite direction. You're back to where you started.")
                time.sleep(2)
                Area2()
            if whatHappends == 2:
                pagemischk = True
                pagemis = True
                print("...After exploring for a little bit, your bag starts.. Glowing?!")
                time.sleep(3)
                print("You open it to see that the shred of paper is glowing a blinding blue.")
                time.sleep(3)
                print("You hold it up and its seemingly pointing towards one of the mirrors?")
                time.sleep(3)
                print("You take it to that mirror and...")
                time.sleep(3)
                print("It gets sucked in?!")
                time.sleep(3)
                print("You try to chAse after it but y0u can't go through the mirror?")
                time.sleep(3)
                print("After a but you decide to let it go.. It wasn't that valuable anyway.. RIght?¿")
                time.sleep(3)
                Area2()
    Area2()
                
            
        

def Area1Desc():
    hp = 50
    heartCards = 0
    healedHp = False
    print(" |              |\n" * 40)
    print("<<‿____________‿>>")
    time.sleep(4)
    print('"owww.."')
    time.sleep(4)
    print("You don't know where you are, it almost feels like a hallucination.")
    time.sleep(4)
    print("You're surrounded with trees that feel like their moving, and a lowly path with rabbit footprints appears infront of you.")
    time.sleep(4)
    def Area1():
        global page1
        global page1chk
        print("Do you want to explore? or follow the p@th?")
        print('Type "BAG" to look inside your bag. Type "STAT" to look at your stats.')
        print("")
        decison = input("EXPL/PATH: ")
        if decison == "STAT":
            print('MAX HP:', hp)
            print("Heart Cards:", heartCards)
            print("InsAnity:: ????????")
            time.sleep(3)
            Area1()
            
        if decison == "BAG":
            print("You had a look in your bag..")
            time.sleep(2)
            if page1chk == False:
                print("But theres nothing in it!\n(You could have sworn there was something in here before)")
                time.sleep(2)
                Area1()
            if page1chk == True:
                print("All there is is the single torn peice of paper.")
                read = input("Read it again? (Y/N):")
                if read == "Y":
                    print("")
                    print("I don.t know where i am. 1t fels like i m ln e dreA\nthis worid i's 1nsame, i do\nESCAP3??????")
                    print("")
                    input("Press Enter to continue")
                    Area1()
                if read == "N":
                    print("You decided not to read it.")
                    Area1()
        if decison == "EXPL":
            print("You decided to explore a little more...")
            if page1 == False:
                whatHappends = random.randint(1,3)
            if page1 == True:
                whatHappends = random.randint(1,2)
            if whatHappends == 1:
                print("...But something approaches!")
                time.sleep(1)
                BLTR.Encounter1()
                Area1()
            if whatHappends == 3:
                page1 = True
                page1chk = True
                print("...You spotted something at the corner of your eye...")
                time.sleep(2)
                print("...a piece of...")
                time.sleep(2)
                print("...paper?")
                time.sleep(2)
                print("You start to read it...")
                time.sleep(2)
                print("")
                print("I don.t know where i am. 1t fels like i m ln e dreA\nthis worid i's 1nsame, i do\nESCAP3??????")
                print("")
                input("Press Enter to continue")
                print("The paper has been ripped up. The handwriting is so sloppy you can barely read it. It was clearly done in a hurry.")
                time.sleep(2)
                print("You decide to keep it in your bag 'till later. You may encounter more.")
                time.sleep(2)
                Area1()
            if whatHappends == 2:
                print("But something approaches!")
                time.sleep(2)
                ROSE.Encounter1()
                Area1()
        if decison == "PATH":
            print("You decided to follow the path...")
            time.sleep(2)
            if page1 == False:
                print("...But you feel like theres something.. Important.. Here. Try exploring a bit more.")
                time.sleep(2)
                Area1()
            if page1 == True:
                print("You encounter a.. Strange looking white rabbit who appears to be in a hurry.")
                time.sleep(4)
                print("")
                print('"Oh dear oh dear Im gonna be late! And Ive gone and lost my way!" He frantically says while looking at a pocket watch.')
                time.sleep(4)
                print("")
                print('"Where are you going?" you asked, hopeful it could lead somewhere useful.')
                time.sleep(4)
                print("")
                print('"Why over where the sun shines the most, and the water flowes roaring from the wall of course! Might you know the way?"')
                time.sleep(4)
                print("")
                print('"I-"')
                time.sleep(3)
                print("")
                print("Your mind becomes a blur as you figure out what he's talking about.")
                time.sleep(4)
                print("You can tell he's getting impatient.")
                time.sleep(4)
                print("")
                print('"Rah! Your useless too! Now Im so gonna be late!" He says as he hopps away.')
                time.sleep(4)
                print("")
                print('"Wait!-" you said as you chased the rabbit.')
                time.sleep(4)
                print("")
                print("You chased the rabbit until you were taken by the fog of.. Some.. Where?")
                time.sleep(4)
                print("You passed out..")
                time.sleep(3)
                print("\n" * 40)
                Area2Desc()
            
    Area1()

Area1Desc()
